# Site settings
title: yjioni
description: yjioni's github blog
baseurl: "https://github.com/yjioni" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ji-Won, Yoon
user_description: I'm a pre-software Engineer from Korea, always trying to improve skills through the 3rd SSAC course.
user_title: Pre-software Engineer
email: oing922@gmail.com
# twitter_username: lorem_ipsum
github_username:  yjioni
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
